services:
  - type: web
    name: attendance-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5002
      - key: ALLOWED_ORIGINS
        value: https://attendance-frontend-mkwg.onrender.com,http://localhost:3000
    healthCheckPath: /api/health
    
  - type: web
    name: attendance-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://attendance-backend-y0rt.onrender.com